name: Deploy Backend Image
run-name: ${{ github.actor }} is deploying a Backend Docker image ðŸš€
permissions:
  contents: write   # allows git push / tag creation
  packages: write
  actions: read
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      backend_version: ${{ steps.backend_version.outputs.version }}
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      # Install dev dependencies
      - name: Install dev deps
        working-directory: ./backend
        run: npm install --only=dev  

      # Run semantic-release to determine the new version
      - name: Run semantic-release
        id: semantic_release        
        working-directory: ./backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
          
      # Get the backend version from the latest tag    
      - name: Get backend version
        id: backend_version
        if: ${{ steps.semantic_release.outcome == 'success' }}
        working-directory: ./backend
        run: |
          if [ -f version.env ]; then
            cat version.env
            VERSION_RAW=$(grep VERSION version.env | cut -d '=' -f2)
            VERSION=${VERSION_RAW#backend-v}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          fi

  build: 
    needs: release
    if: ${{ needs.release.outputs.backend_version != '' }}
    runs-on: ubuntu-latest       
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub  
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  

      # Get the Docker Buildx action set up  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push the Backend Docker image    
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/personal-website-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/personal-website-backend:${{ needs.release.outputs.backend_version }}

      # Log out from Docker Hub
      - name: Log out from Docker Hub
        run: docker logout    
